# Generated by Django 3.2.10 on 2022-02-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0004_contato_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='id_by_user',
            field=models.IntegerField(null=True),
        ),
    ]
